# Generated by Django 6.0 on 2026-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheda_id', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valutazioni', models.JSONField()),
                ('conteggi', models.JSONField()),
                ('single_workload', models.JSONField()),
                ('percentuali', models.JSONField()),
                ('totale_workload', models.FloatField()),
                ('overall', models.FloatField()),
            ],
        ),
    ]
