# Generated by Django 6.0 on 2026-05-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_test_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
